version: '2'

services:
  devpi:
    build:
      context: .
      dockerfile: ./compose/devpi/Dockerfile
    volumes:
      - ./data:/data
    env_file: .env
    ports:
      - "3141:3141"
    restart: always
